# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "2"

services:
  hub-db:
    image: postgres:9.5
    container_name: jupyterhub-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${DB_VOLUME_CONTAINER}
    env_file:
      - secrets/postgres.env
    volumes:
      - "db:${DB_VOLUME_CONTAINER}"

  hub:
    depends_on:
      - hub-db
#    build:
#      context: .
#      dockerfile: Dockerfile.jupyterhub
#      args:
#        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
    restart: always
    image: cuahsi/jupyterhub
    container_name: jupyterhub
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "data:${DATA_VOLUME_CONTAINER}"
      # Bind userspace on host to Jupyter container (tony)
      - "${JUPYTER_USERSPACE_DIR_HOST}:${JUPYTER_USERSPACE_DIR}:rw"
      # Mount jupyter configuration (tony)
      - "./config/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
    ports:
      - "443:443"
    links:
      - hub-db
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: ${LOCAL_NOTEBOOK_IMAGE}
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      # Using this run command (optional)
      DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}
      # Postgres db info
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: hub-db
      # Extra JupyterHub (Tony)
      JUPYTER_USERSPACE_DIR: ${JUPYTER_USERSPACE_DIR}
      JUPYTER_USER: ${JUPYTER_USER}
      JUPYTER_NOTEBOOK_DIR: ${JUPYTER_NOTEBOOK_DIR}  
#      USERDATA_VOLUME_CONTAINER: ${USERDATA_VOLUME_CONTAINER}
#      USERDATA_VOLUME_HOST: ${USERDATA_VOLUME_HOST}
      JUPYTER_USERSPACE_DIR_HOST: ${JUPYTER_USERSPACE_DIR_HOST}
#      OAUTH_CALLBACK_URL: ${OAUTH_CALLBACK_URL}
    env_file:
      - secrets/postgres.env
      - secrets/oauth.env
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
  jupyterhub_rest:
    image: cuahsi/jupyterhub-rest:latest
    volumes:
       # Bind userspace on host to Jupyter container (tony)
       - "${JUPYTER_USERSPACE_DIR_HOST}:${JUPYTER_USERSPACE_DIR}:rw"
    ports:
       - "8080:8080"
    environment:
       HYDROSHARE_REDIRECT_COOKIE_PATH: ${JUPYTER_USERSPACE_DIR}/_global/jupyterhub/redirect
       JUPYTER_HUB_IP: jupyter-w2.cuahsi.org
       JUPYTER_PORT: 80
       JUPYTER_NOTEBOOK_DIR: ${JUPYTER_NOTEBOOK_DIR}
       JUPYTER_USERSPACE_DIR: ${JUPYTER_USERSPACE_DIR_HOST}
#       - JUPYTER_NOTEBOOK_DIR=/remote/data/userspace/_global/notebooks
#       - JUPYTER_USERSPACE_DIR=/remote/data/userspace
       JUPYTER_USER: root
       JUPYTER_REST_IP: jupyter-w2.cuahsi.org
       JUPYTER_REST_PORT: 8080
       SSL_ENABLED: 0
       SSL_CERT: None
       SSL_KEY: None
#      volumes:
#          - type: bind
#            source: /remote/data/userspace
#            target: /remote/data/userspace
#      networks:
#          - jhub
volumes:
  data:
    external:
      name: ${DATA_VOLUME_HOST}
  db:
    external:
      name: ${DB_VOLUME_HOST}

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
